name: Flight Tracker

on:
  schedule:
    # Run every 10 minutes
    - cron: '*/10 * * * *'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  track-flights:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
      - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run flight tracker
      env:
        # Email configuration - set these in GitHub repository secrets
        OUTLOOK_EMAIL: ${{ secrets.OUTLOOK_EMAIL }}
        OUTLOOK_PASSWORD: ${{ secrets.OUTLOOK_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      run: python main.py
